feat: updates terraform plan and apply workflows to be simpler and effective

diff --git a/.github/workflows/01-terraform-plan.yml b/.github/workflows/01-terraform-plan.yml
--- a/.github/workflows/01-terraform-plan.yml
+++ b/.github/workflows/01-terraform-plan.yml
@@ -27,12 +27,16 @@ jobs:
     runs-on: ubuntu-latest
     name: ${{ matrix.images.name }}
     steps:
+      - name: Fail Workflow if secrets not defined
+        shell: bash
+        run: |
+          if [ -z "${{ secrets.ENCRYPTION_PASSWORD }}" ]; then
+            echo "Error: secret ENCRYPTION_PASSWORD is missing. This secret must be set, to encrypt the terraform plan prior to uploading to github artifacts" >&2
+            exit 1
+          fi
+
       - name: Checkout
         uses: actions/checkout@v4
-
-      - uses: sersoft-gmbh/setup-gh-cli-action@v2
-        with:
-          version: latest
 
       - uses: nxtcoder17/actions/pull-request-create@feat/tf-issues-and-pr
         id: pr
@@ -41,84 +45,56 @@ jobs:
           title: ${{ env.GITHUB_PR_TITLE }}
           body: "this PR once merged, audits, and tracks the terraform IAC changes"
 
+      - name: creating output directory
+        shell: bash
+        id: output-dir
+        run: |
+          pushd "${{ inputs.dir }}"
+          mkdir -p .actions-output
+          plan_output_dir="$PWD/.actions-output"
+          echo "TF_PLAN_OUTPUT_DIR=$plan_output_dir" | tee -a $GITHUB_ENV
+          popd
+
+          echo "${{inputs.dir}}" > $plan_output_dir/tf-working-dir
+
       - uses: nxtcoder17/actions/terraform-plan@feat/tf-issues-and-pr
+        id: plan
         with:
           github_token: ${{ env.GITHUB_TOKEN }}
           working_directory: ${{ inputs.dir }}
           terraform_version: ${{ inputs.terraform_version  }}
           pr_number: ${{ steps.pr.outputs.PR_NUMBER }}
+          plan_file: "${{ env.TF_PLAN_OUTPUT_DIR }}/tfplan"
 
-      # - name: create a PR related to this
-      #   id: pr
-      #   shell: bash
-      #   run: |+
-      #     gh --version
-      #     gh pr list --json title,number,id -q "map(select(.title == \"$GITHUB_PR_TITLE\")) | first | .number // \"Not Found\"" > pr_number.txt
-      #     gh pr list --json title,number,id -q "map(select(.title == \"$GITHUB_PR_TITLE\")) | first | .id // \"Not Found\"" > pr_id.txt
-      #
-      #     test "$pr" = "Not Found" && echo "creating new PR" && gh pr create --title "$GITHUB_PR_TITLE" --body "this PR once merged, audits, and tracks the terraform IAC changes"
-      #
-      #     gh pr list --json title,number,id -q "map(select(.title == \"$GITHUB_PR_TITLE\")) | first | .number // \"Not Found\"" > pr_number.txt
-      #     gh pr list --json title,number,id -q "map(select(.title == \"$GITHUB_PR_TITLE\")) | first | .id // \"Not Found\"" > pr_id.txt
-      #     pr_number=$(cat pr_number.txt)
-      #     pr_id=$(cat pr_id.txt)
-      #
-      #     echo "PR_ID: $pr_id | PR_NUMBER: $pr_number"
-      #     echo "pr_id=$pr_id" >> $GITHUB_OUTPUT
-      #     echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
-      #
-      # - name: Setup Terraform
-      #   uses: hashicorp/setup-terraform@v3
-      #   with:
-      #     terraform_version: ${{ inputs.terraform_version }}
-      #     terraform_wrapper: false
-      #
-      # - name: Terraform Init
-      #   id: init
-      #   working-directory: ${{ inputs.dir }}
-      #   shell: bash
-      #   run: |
-      #     terraform init -reconfigure
-      #
-      # - name: Terraform Plan
-      #   id: plan
-      #   working-directory: ${{ inputs.dir }}
-      #   shell: bash
-      #   run: |
-      #     plan_dir="$PWD/.out"
-      #     mkdir $plan_dir
-      #     echo 'plan<<EOF' >> $GITHUB_OUTPUT
-      #     terraform plan -no-color -out=$plan_dir/tfplan >> $GITHUB_OUTPUT
-      #     echo 'EOF' >> $GITHUB_OUTPUT
-      #
-      #     echo "${{ inputs.dir }}" > $plan_dir/working-dir
-      #
-      #     echo "plan_dir=$plan_dir"
-      #     ls -al $plan_dir
-      #
-      #     echo "PLAN_DIR=$plan_dir" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
-      #
-      # - name: Save Artifact
-      #   id: save-artifact
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: ${{ steps.pr.outputs.pr_number }}-tf
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     path: |
-      #       ${{ steps.plan.outputs.PLAN_DIR }}/tfplan
-      #       ${{ steps.plan.outputs.PLAN_DIR }}/working-dir
-      #
-      # - name: Comment Plan
-      #   id: comment-plan
-      #   uses: peter-evans/create-or-update-comment@v2
-      #   with:
-      #     token: ${{ env.GITHUB_TOKEN }}
-      #     issue-number: ${{ steps.pr.outputs.pr_number }}
-      #     body: |
-      #       Terraform Plan:
-      #
-      #       ```
-      #       ${{ steps.plan.outputs.plan }}
-      #       ```
-      #
-      #       Plan has been saved to GH artifacts.
+      - name: encrypt terraform plan 
+        shell: bash
+        run: |
+          echo "encrypting terraform plan file using AES-256-CBC algorithm"
+          pushd "${{ env.TF_PLAN_OUTPUT_DIR }}"
+          openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -in tfplan -out "tfplan.enc" -pass pass:"${{ secrets.ENCRYTPTION_PASSWORD }}"
+          mv tfplan.enc tfplan
+          popd
+
+      - name: Save Artifact
+        id: save-plan
+        uses: actions/upload-artifact@v4
+        with:
+          name: ${{ steps.pr.outputs.PR_NUMBER }}-tf
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          path: |
+            ${{ env.TF_PLAN_OUTPUT_DIR }}/tfplan
+            ${{ env.TF_PLAN_OUTPUT_DIR }}/tf-working-dir
+
+      - name: Terraform Plan Comment
+        uses: nxtcoder17/actions/issue-comment@feat/tf-issues-and-pr
+        with:
+          github_token: ${{ inputs.GITHUB_TOKEN }}
+          issue_number: ${{ steps.pr.outputs.PR_NUMBER }}
+          body: |
+            Terraform Plan:
+
+            ```
+            ${{ steps.plan.outputs.TF_PLAN_STDOUT }}
+            ```
+
+            Terraform Plan has been securely encrypted and uploaded to [Github Artifacts](steps.save-plan.outputs.artifact-url)
diff --git a/.github/workflows/02-terraform-apply.yml b/.github/workflows/02-terraform-apply.yml
--- a/.github/workflows/02-terraform-apply.yml
+++ b/.github/workflows/02-terraform-apply.yml
@@ -32,83 +32,97 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Get PR branch (if workflow_dispatch)
-        if: ${{ github.event_name == 'workflow_dispatch' }}
-        run: |+
-          echo "PR_NUMBER=${{ inputs.pr_number }}" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
-          gh pr list --json headRefName,number -q "map(select(.number == ${{inputs.pr_number}} )) | first | .headRefName // \"Not Found\"" > pr_branch.txt
-          pr_branch=$(cat pr_branch.txt)
-          echo "PR_BRANCH=$pr_branch" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
+      - name: Fail Workflow if secrets not defined
+        shell: bash
+        run: |
+          if [ -z "${{ secrets.ENCRYPTION_PASSWORD }}" ]; then
+            echo "Error: secret ENCRYPTION_PASSWORD is missing. This secret must be set, to decrypt the downloaded terraform plan file" >&2
+            exit 1
+          fi
 
-      - name: Get PR branch (if !workflow_dispatch)
-        if: ${{ github.event_name != 'workflow_dispatch' }}
-        run: |+
-          pr_number=$( echo ${{ github.ref }} | sed 's/refs[/]pull[/]//' | sed 's/[/]merge//' )
-          gh pr list --json headRefName,number -q "map(select(.number == $pr_number )) | first | .headRefName // \"Not Found\"" > pr_branch.txt
-          pr_branch=$(cat pr_branch.txt)
-
-          echo "PR_NUMBER=$pr_number" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
-          echo "PR_BRANCH=$pr_branch" | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT
+      - name: Get PR Branch
+        uses: nxtcoder17/actions/pull-request-branch@feat/tf-issues-and-pr
+        id: pr
+        with:
+          github_token: ${{ env.GITHUB_TOKEN }}
+          # inputs.pr_number will only be set, when using workflow-dispatch
+          pull_request_number: ${{ inputs.pr_number }}
 
       - name: Checkout
         uses: actions/checkout@v4
         with:
-          ref: ${{ env.PR_BRANCH }}
+          ref: ${{ steps.pr.outputs.PR_BRANCH }}
 
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v3
+      - name: Download Created Plan
+        uses: nxtcoder17/actions/download-workflow-artifact@feat/tf-issues-and-pr
         with:
-          terraform_version: ${{ inputs.terraform_version }}
-          terraform_wrapper: false
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          workflow_name: 01-terraform-plan.yml
+          artifact_name: ${{ steps.pr.outputs.PR_NUMBER }}-tf
+          destination: ".tfplan"
 
-
-      - name: Download Plan from github artifacts
-        id: download-plan
+      - name: Decrypt Downloaded Terraform Plan file
         shell: bash
-        run: |+
-          run_id=$(gh run ls --workflow=01-terraform-plan.yml --json number,databaseId -q 'first | .databaseId')
-          gh run download $run_id -n ${{env.PR_NUMBER}}-tf -D ./out
+        id: plan-output
+        run: |
+          pushd .tfplan
+          openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 -in tfplan -out "tfplan.dec" -pass pass:"${{ secrets.ENCRYTPTION_PASSWORD }}"
+          mv tfplan.dec tfplan
+          popd
 
-        # uses: actions/download-artifact@v4
-        # with:
-        #   name: ${{ env.PR_NUMBER }}-tf
-        #   path: ./out
-        #   github-token: ${{ secrets.GITHUB_TOKEN }}
+          echo "TF_WORKING_DIR=$(cat .tfplan/tf-working-dir)" | tee -a $GITHUB_ENV
+          echo "TF_PLAN_FILE=$(echo $PWD/.tfplan/tfplan)" | tee -a $GITHUB_ENV
 
-      - name: ls
-        shell: bash
-        run: |+
-          ls -al ./out
-
-      - name: Terraform Init
-        id: init
+      - name: Decrypt terraform state (if present)
         shell: bash
         run: |
-          pushd $(cat out/working-dir)
-          terraform init
+          pushd ${{ env.TF_WORKING_DIR }}
+
+          if [ -f terraform.tfstate ]; then
+            openssl enc -d -aes-256-cbc -pbkdf2 -iter 600000 -in terraform.tfstate -out "terraform.tfstate.dec" -pass pass:"${{ secrets.ENCRYTPTION_PASSWORD }}"
+            mv terraform.tfstate.dec terraform.tfstate
+          fi
           popd
 
       - name: Terraform Apply
+        uses: nxtcoder17/actions/terraform-apply@feat/tf-issues-and-pr
         id: apply
+        with:
+          terraform_version: ${{ inputs.terraform_version }}
+          working_directory: ${{ env.TF_WORKING_DIR }}
+          plan_file: ${{ env.TF_PLAN_FILE }}
+
+      - name: Encrypt terraform state
         shell: bash
         run: |
-          tfplan="$PWD/out/tfplan"
-          pushd $(cat out/working-dir)
-          echo 'apply<<EOF' >> $GITHUB_OUTPUT
-          terraform apply -input=false -no-color $tfplan >> $GITHUB_OUTPUT
-          echo 'EOF' >> $GITHUB_OUTPUT
+          pushd ${{ env.TF_WORKING_DIR }}
+          # aes-256-gcm did not work
+          openssl enc -aes-256-cbc -pbkdf2 -iter 600000 -in terraform.tfstate -out "terraform.tfstate.enc" -pass pass:"${{ secrets.ENCRYTPTION_PASSWORD }}"
+          mv terraform.tfstate.enc terraform.tfstate
           popd
 
-      - name: Comment Apply
-        id: comment-apply
-        uses: peter-evans/create-or-update-comment@v2
+        # Step 6: Pushing Encrypted State File Back to PR Branch
+      - name: Configure Git
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+
+      - name: Commit and Push Encrypted State File
+        run: |
+          git add ${{ env.TF_WORKING_DIR }}/terraform.tfstate
+          git commit -m "Update encrypted Terraform state file"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Comment on PR
+        uses: nxtcoder17/actions/issue-comment@feat/tf-issues-and-pr
         with:
-          token: ${{ env.GITHUB_TOKEN }}
-          issue-number: ${{ env.PR_NUMBER }}
+          github_token: ${{ inputs.GITHUB_TOKEN }}
+          issue_number: ${{ steps.pr.outputs.PR_NUMBER }}
           body: |
             Terraform Apply:
 
             ```
-            ${{ steps.apply.outputs.apply }}
+            ${{ steps.apply.outputs.TF_APPLY_STDOUT }}
             ```
-
